apiVersion: skaffold/v1beta13
build:
  artifacts:
  - context: .
    docker:
      dockerfile: Dockerfile
    image: gcr.io/dst-mlpipes/pjm_pipeline_ol653374
  tagPolicy:
    envTemplate:
      template: latest
kind: Config
